### PR TITLE
Restructure folder tree

### LINKED ISSUE #53: [Feature Request] Improve the folder tree order
## Description
Consider to improve the folder tree order, right now, the services: Bots, SlackInterop ,DataStorage, they are separated, they
could be in a common directory to set more clearly up the responsibility.

## Describe the solution you'd like
It can be grouped in the folder as, for example: Services, Data, or something that groups all the services and the data layer in one place. Idea:
┣ Services
┃ ┣ Bots
┃ ┗ SlackService.cs
┣ Data
┃ ┗ DataStorage.cs
┣ ...

### PR DESCRIPTION
**Pull request by nelsonsouthworks**
Fixes #53 
## Description
The folder tree structure was restructured. Grouping items of the same type to clarify responsibilities.

## Specific Changes
  - The project folder tree has been restructured.
  - Grouping by the same responsibility type for the data layer and the communication with external services.
  - Changed from `DataStorage` folder to `Data`
  - Created the `Service` folder
  - Moved the **interfaces** and **implementations** to the `Service` folder

## Aditional content
image

### CODE REVIEW

**Review by angelszymczak — CHANGES_REQUESTED** [review]
The PR is OK,
but I suggest adding a screenshot of the old structure folder tree compared to the new one.

**Comment by dfavretto** [comment]
What criteria did you use to define if something goes to `Services` folder or `Data` folder? For example, why you moved `BlobContainerConversationStore` into `Services` folder and not `Data` along with `BambooUsersStorageInterop` as they are both related to Storage?

**Comment by nelsonsouthworks** [comment]
Hi @dfavretto, I had taken `BlobContainerConversationStore` as the implementation, along with `IStore` as the interface. That is why I included it in the Service section.

**Comment by angelszymczak** [comment]
I found a typo on the PR description.
image

And I take the opportunity to suggest another description
> The project folder tree has been restructured.
> Grouping by the same responsibility type for the data layer and the communication with external services.

**Review by angelszymczak — CHANGES_REQUESTED** [review]
Request by fix typo on PR description
image

**Comment by gonzalorieto** [comment]
I reviewed the proposal changes and my suggestion is to close this PR and fix some other things first before moving stuff around.
I opened the [issue#58](https://github.com/southworks/azure-botsdk-happybirthday-bamboohr-slack-bot/issues/58). This issue should be fixed first before improving the project file structure.

Also, there are some other minor issues that we should take a look first, such as:
- Naming conventions issues.
- Code styling
- Code repetition

**Comment by dfavretto** [comment]
> I reviewed the proposal changes and my suggestion is to close this PR and fix some other things first before moving stuff around.
> I opened the [issue#58](https://github.com/southworks/azure-botsdk-happybirthday-bamboohr-slack-bot/issues/58). This issue should be fixed first before improving the project file structure.
> 
> Also, there are some other minor issues that we should take a look first, such as:
> 
> * Naming conventions issues.
> * Code styling
> * Code repetition

I agree there are other things to fix, but having this PR already created and ready to be merged, I wouldn't discard it, but merge it and work on those other fixes later on. Look at this folder movement as the first step to fixing all the styling, once the files are in the correct place, then they can be fixed in the inside, thus keeping the history of the new changes. If you move the files at the end, you lose the history of the changes.

**Review by dfavretto — APPROVED** [review]

**Pull request merged**
